# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Practical' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Practical
  pod 'IQKeyboardManager', '~> 6.5'
  pod 'AlamofireObjectMapper', '~> 5.2'
  pod 'SDWebImage', '~> 4.3.3'
  pod 'KRProgressHUD', '~> 3.4.5'


end
